/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.david.messages;

import org.openmuc.jasn1.ber.types.BerInteger;


public class BinaryTime extends BerInteger {

    public BinaryTime() {
    }

    public BinaryTime(byte[] code) {
        super(code);
    }

    public BinaryTime(long value) {
        super(value);
    }

}
