/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.david.messages;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.BerIdentifier;
import org.openmuc.jasn1.ber.BerLength;
import org.openmuc.jasn1.ber.types.BerEnum;

import java.io.IOException;
import java.io.InputStream;


public class Logical {

    public static final BerIdentifier identifier = new BerIdentifier(BerIdentifier.APPLICATION_CLASS, BerIdentifier.CONSTRUCTED, 5);
    public byte[] code = null;
    public BerEnum op = null;
    public Query l = null;
    public Query r = null;
    protected BerIdentifier id;

    public Logical() {
        id = identifier;
    }

    public Logical(byte[] code) {
        id = identifier;
        this.code = code;
    }

    public Logical(BerEnum op, Query l, Query r) {
        id = identifier;
        this.op = op;
        this.l = l;
        this.r = r;
    }

    public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                os.write(code[i]);
            }
        } else {
            codeLength = 0;
            codeLength += r.encode(os, true);

            codeLength += l.encode(os, true);

            codeLength += op.encode(os, true);

            codeLength += BerLength.encodeLength(os, codeLength);
        }

        if (explicit) {
            codeLength += id.encode(os);
        }

        return codeLength;

    }

    public int decode(InputStream is, boolean explicit) throws IOException {
        int codeLength = 0;
        int subCodeLength = 0;
        BerIdentifier berIdentifier = new BerIdentifier();

        if (explicit) {
            codeLength += id.decodeAndCheck(is);
        }

        BerLength length = new BerLength();
        codeLength += length.decode(is);

        int totalLength = length.val;
        codeLength += totalLength;

        subCodeLength += berIdentifier.decode(is);
        if (berIdentifier.equals(BerEnum.identifier)) {
            op = new BerEnum();
            subCodeLength += op.decode(is, false);
            subCodeLength += berIdentifier.decode(is);
        } else {
            throw new IOException("Identifier does not match the mandatory sequence element identifer.");
        }

        l = new Query();
        subCodeLength += l.decode(is, berIdentifier);
        subCodeLength += berIdentifier.decode(is);

        r = new Query();
        subCodeLength += r.decode(is, berIdentifier);
        if (subCodeLength == totalLength) {
            return codeLength;
        }
        throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);


    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
        encode(os, false);
        code = os.getArray();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder("SEQUENCE{");
        sb.append("op: ").append(op);

        sb.append(", ");
        sb.append("l: ").append(l);

        sb.append(", ");
        sb.append("r: ").append(r);

        sb.append("}");
        return sb.toString();
    }

}

