/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.david.messages;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.BerIdentifier;
import org.openmuc.jasn1.ber.BerLength;

import java.io.IOException;
import java.io.InputStream;


public class Message {

    public byte[] code = null;
    public AssessmentRequest assessmentRequest = null;

    public AssessmentResponse assessmentResponse = null;

    public TrustRequest trustRequest = null;

    public TrustResponse trustResponse = null;

    public FormatRequest formatRequest = null;

    public FormatResponse formatResponse = null;

    public Error error = null;

    public Message() {
    }

    public Message(byte[] code) {
        this.code = code;
    }

    public Message(AssessmentRequest assessmentRequest, AssessmentResponse assessmentResponse, TrustRequest trustRequest, TrustResponse trustResponse, FormatRequest formatRequest, FormatResponse formatResponse, Error error) {
        this.assessmentRequest = assessmentRequest;
        this.assessmentResponse = assessmentResponse;
        this.trustRequest = trustRequest;
        this.trustResponse = trustResponse;
        this.formatRequest = formatRequest;
        this.formatResponse = formatResponse;
        this.error = error;
    }

    public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {
        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                os.write(code[i]);
            }
            return code.length;

        }
        int codeLength = 0;
        if (error != null) {
            codeLength += error.encode(os, true);
            return codeLength;

        }

        if (formatResponse != null) {
            codeLength += formatResponse.encode(os, true);
            return codeLength;

        }

        if (formatRequest != null) {
            codeLength += formatRequest.encode(os, true);
            return codeLength;

        }

        if (trustResponse != null) {
            codeLength += trustResponse.encode(os, true);
            return codeLength;

        }

        if (trustRequest != null) {
            codeLength += trustRequest.encode(os, true);
            return codeLength;

        }

        if (assessmentResponse != null) {
            codeLength += assessmentResponse.encode(os, true);
            return codeLength;

        }

        if (assessmentRequest != null) {
            codeLength += assessmentRequest.encode(os, true);
            return codeLength;

        }

        throw new IOException("Error encoding BerChoice: No item in choice was selected.");
    }

    public int decode(InputStream is, BerIdentifier berIdentifier) throws IOException {
        int codeLength = 0;
        BerIdentifier passedIdentifier = berIdentifier;

        if (berIdentifier == null) {
            berIdentifier = new BerIdentifier();
            codeLength += berIdentifier.decode(is);
        }

        BerLength length = new BerLength();
        if (berIdentifier.equals(AssessmentRequest.identifier)) {
            assessmentRequest = new AssessmentRequest();
            codeLength += assessmentRequest.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(AssessmentResponse.identifier)) {
            assessmentResponse = new AssessmentResponse();
            codeLength += assessmentResponse.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(TrustRequest.identifier)) {
            trustRequest = new TrustRequest();
            codeLength += trustRequest.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(TrustResponse.identifier)) {
            trustResponse = new TrustResponse();
            codeLength += trustResponse.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(FormatRequest.identifier)) {
            formatRequest = new FormatRequest();
            codeLength += formatRequest.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(FormatResponse.identifier)) {
            formatResponse = new FormatResponse();
            codeLength += formatResponse.decode(is, false);
            return codeLength;
        }

        if (berIdentifier.equals(Error.identifier)) {
            error = new Error();
            codeLength += error.decode(is, false);
            return codeLength;
        }

        if (passedIdentifier != null) {
            return 0;
        }
        throw new IOException("Error decoding BerChoice: Identifier matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
        encode(os, false);
        code = os.getArray();
    }

    public String toString() {
        if (assessmentRequest != null) {
            return "CHOICE{assessmentRequest: " + assessmentRequest + "}";
        }

        if (assessmentResponse != null) {
            return "CHOICE{assessmentResponse: " + assessmentResponse + "}";
        }

        if (trustRequest != null) {
            return "CHOICE{trustRequest: " + trustRequest + "}";
        }

        if (trustResponse != null) {
            return "CHOICE{trustResponse: " + trustResponse + "}";
        }

        if (formatRequest != null) {
            return "CHOICE{formatRequest: " + formatRequest + "}";
        }

        if (formatResponse != null) {
            return "CHOICE{formatResponse: " + formatResponse + "}";
        }

        if (error != null) {
            return "CHOICE{error: " + error + "}";
        }

        return "unknown";
    }

}

