/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.david.messages;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.types.BerEnum;

import java.io.IOException;


public class QTM extends BerEnum {

    public QTM() {
    }

    public QTM(byte[] code) {
        super(code);
    }

    public QTM(long value) {
        super(value);
    }

    public void encodeAndSave() throws IOException {
        BerByteArrayOutputStream os = new BerByteArrayOutputStream(3);
        this.encode(os, true);
        code = os.getArray();
    }
}
