/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.david.messages;

import org.openmuc.jasn1.ber.types.string.BerPrintableString;


public class Service extends BerPrintableString {

    public Service() {
    }

    public Service(byte[] value) {
        super(value);
    }

}
