/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.types.BerInteger;

import java.math.BigInteger;


public class BinaryTime extends BerInteger {

    public BinaryTime() {
    }

    public BinaryTime(byte[] code) {
        super(code);
    }

    public BinaryTime(BigInteger value) {
        super(value);
    }

    public BinaryTime(long value) {
        super(value);
    }

}
