/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.types.string.BerIA5String;


public class Entity extends BerIA5String {

    private static final long serialVersionUID = 1L;

    public Entity() {
    }

    public Entity(byte[] value) {
        super(value);
    }

}
