/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;


public class Format extends BerObjectIdentifier {

    private static final long serialVersionUID = 1L;

    public Format() {
    }

    public Format(byte[] code) {
        super(code);
    }

    public Format(int[] value) {
        super(value);
    }

}
