/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.BerIdentifier;
import org.openmuc.jasn1.ber.types.BerNull;


public class FormatRequest extends BerNull {

    public static final BerIdentifier identifier = new BerIdentifier(BerIdentifier.APPLICATION_CLASS, BerIdentifier.PRIMITIVE, 0);

    public FormatRequest() {
        id = identifier;
    }

    public FormatRequest(byte[] code) {
        super(code);
        id = identifier;
    }

}
