/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.BerLength;
import org.openmuc.jasn1.ber.BerTag;
import org.openmuc.jasn1.ber.types.BerInteger;
import org.openmuc.jasn1.ber.types.string.BerPrintableString;

import java.io.IOException;
import java.io.InputStream;


public class FormatResponse {

    public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 1);

    public byte[] code = null;
    public BerInteger rid = null;
    public Format format = null;
    public BerPrintableString assessment = null;
    public BerPrintableString trust = null;

    public FormatResponse() {
    }

    public FormatResponse(byte[] code) {
        this.code = code;
    }

    public FormatResponse(BerInteger rid, Format format, BerPrintableString assessment, BerPrintableString trust) {
        this.rid = rid;
        this.format = format;
        this.assessment = assessment;
        this.trust = trust;
    }

    public int encode(BerByteArrayOutputStream os) throws IOException {
        return encode(os, true);
    }

    public int encode(BerByteArrayOutputStream os, boolean withTag) throws IOException {

        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                os.write(code[i]);
            }
            if (withTag) {
                return tag.encode(os) + code.length;
            }
            return code.length;
        }

        int codeLength = 0;
        codeLength += trust.encode(os, true);

        codeLength += assessment.encode(os, true);

        codeLength += format.encode(os, true);

        codeLength += rid.encode(os, true);

        codeLength += BerLength.encodeLength(os, codeLength);

        if (withTag) {
            codeLength += tag.encode(os);
        }

        return codeLength;

    }

    public int decode(InputStream is) throws IOException {
        return decode(is, true);
    }

    public int decode(InputStream is, boolean withTag) throws IOException {
        int codeLength = 0;
        int subCodeLength = 0;
        BerTag berTag = new BerTag();

        if (withTag) {
            codeLength += tag.decodeAndCheck(is);
        }

        BerLength length = new BerLength();
        codeLength += length.decode(is);

        int totalLength = length.val;
        codeLength += totalLength;

        subCodeLength += berTag.decode(is);
        if (berTag.equals(BerInteger.tag)) {
            rid = new BerInteger();
            subCodeLength += rid.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(Format.tag)) {
            format = new Format();
            subCodeLength += format.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(BerPrintableString.tag)) {
            assessment = new BerPrintableString();
            subCodeLength += assessment.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(BerPrintableString.tag)) {
            trust = new BerPrintableString();
            subCodeLength += trust.decode(is, false);
            if (subCodeLength == totalLength) {
                return codeLength;
            }
        }
        throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);


    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
        encode(os, false);
        code = os.getArray();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder("SEQUENCE{");
        sb.append("rid: ").append(rid);

        sb.append(", ");
        sb.append("format: ").append(format);

        sb.append(", ");
        sb.append("assessment: ").append(assessment);

        sb.append(", ");
        sb.append("trust: ").append(trust);

        sb.append("}");
        return sb.toString();
    }

}

