/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.BerLength;
import org.openmuc.jasn1.ber.BerTag;
import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jasn1.ber.types.BerInteger;
import org.openmuc.jasn1.ber.types.BerType;
import org.openmuc.jasn1.ber.types.string.BerIA5String;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class FormatResponse implements BerType, Serializable {

    public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 1);
    private static final long serialVersionUID = 1L;
    public byte[] code = null;
    public BerInteger rid = null;
    public Format assessmentId = null;
    public BerIA5String assessmentDef = null;
    public Format trustId = null;
    public BerIA5String trustDef = null;

    public FormatResponse() {
    }

    public FormatResponse(byte[] code) {
        this.code = code;
    }

    public FormatResponse(BerInteger rid, Format assessmentId, BerIA5String assessmentDef, Format trustId, BerIA5String trustDef) {
        this.rid = rid;
        this.assessmentId = assessmentId;
        this.assessmentDef = assessmentDef;
        this.trustId = trustId;
        this.trustDef = trustDef;
    }

    public int encode(OutputStream reverseOS) throws IOException {
        return encode(reverseOS, true);
    }

    public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                reverseOS.write(code[i]);
            }
            if (withTag) {
                return tag.encode(reverseOS) + code.length;
            }
            return code.length;
        }

        int codeLength = 0;
        codeLength += trustDef.encode(reverseOS, true);

        codeLength += trustId.encode(reverseOS, true);

        codeLength += assessmentDef.encode(reverseOS, true);

        codeLength += assessmentId.encode(reverseOS, true);

        codeLength += rid.encode(reverseOS, true);

        codeLength += BerLength.encodeLength(reverseOS, codeLength);

        if (withTag) {
            codeLength += tag.encode(reverseOS);
        }

        return codeLength;

    }

    public int decode(InputStream is) throws IOException {
        return decode(is, true);
    }

    public int decode(InputStream is, boolean withTag) throws IOException {
        int codeLength = 0;
        int subCodeLength = 0;
        BerTag berTag = new BerTag();

        if (withTag) {
            codeLength += tag.decodeAndCheck(is);
        }

        BerLength length = new BerLength();
        codeLength += length.decode(is);

        int totalLength = length.val;
        codeLength += totalLength;

        subCodeLength += berTag.decode(is);
        if (berTag.equals(BerInteger.tag)) {
            rid = new BerInteger();
            subCodeLength += rid.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(Format.tag)) {
            assessmentId = new Format();
            subCodeLength += assessmentId.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(BerIA5String.tag)) {
            assessmentDef = new BerIA5String();
            subCodeLength += assessmentDef.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(Format.tag)) {
            trustId = new Format();
            subCodeLength += trustId.decode(is, false);
            subCodeLength += berTag.decode(is);
        } else {
            throw new IOException("Tag does not match the mandatory sequence element tag.");
        }

        if (berTag.equals(BerIA5String.tag)) {
            trustDef = new BerIA5String();
            subCodeLength += trustDef.decode(is, false);
            if (subCodeLength == totalLength) {
                return codeLength;
            }
        }
        throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);


    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(reverseOS, false);
        code = reverseOS.getArray();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendAsString(sb, 0);
        return sb.toString();
    }

    public void appendAsString(StringBuilder sb, int indentLevel) {

        sb.append("{");
        sb.append("\n");
        for (int i = 0; i < indentLevel + 1; i++) {
            sb.append("\t");
        }
        if (rid != null) {
            sb.append("rid: ").append(rid);
        } else {
            sb.append("rid: <empty-required-field>");
        }

        sb.append(",\n");
        for (int i = 0; i < indentLevel + 1; i++) {
            sb.append("\t");
        }
        if (assessmentId != null) {
            sb.append("assessmentId: ").append(assessmentId);
        } else {
            sb.append("assessmentId: <empty-required-field>");
        }

        sb.append(",\n");
        for (int i = 0; i < indentLevel + 1; i++) {
            sb.append("\t");
        }
        if (assessmentDef != null) {
            sb.append("assessmentDef: ").append(assessmentDef);
        } else {
            sb.append("assessmentDef: <empty-required-field>");
        }

        sb.append(",\n");
        for (int i = 0; i < indentLevel + 1; i++) {
            sb.append("\t");
        }
        if (trustId != null) {
            sb.append("trustId: ").append(trustId);
        } else {
            sb.append("trustId: <empty-required-field>");
        }

        sb.append(",\n");
        for (int i = 0; i < indentLevel + 1; i++) {
            sb.append("\t");
        }
        if (trustDef != null) {
            sb.append("trustDef: ").append(trustDef);
        } else {
            sb.append("trustDef: <empty-required-field>");
        }

        sb.append("\n");
        for (int i = 0; i < indentLevel; i++) {
            sb.append("\t");
        }
        sb.append("}");
    }

}

