/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.types.BerEnum;

import java.math.BigInteger;


public class QTM extends BerEnum {

    public QTM() {
    }

    public QTM(byte[] code) {
        super(code);
    }

    public QTM(BigInteger value) {
        super(value);
    }

    public QTM(long value) {
        super(value);
    }

}
