/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.BerTag;
import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jasn1.ber.types.BerType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class Query implements BerType, Serializable {

    private static final long serialVersionUID = 1L;

    public byte[] code = null;
    public Constraint con = null;
    public Expression exp = null;

    public Query() {
    }

    public Query(byte[] code) {
        this.code = code;
    }

    public Query(Constraint con, Expression exp) {
        this.con = con;
        this.exp = exp;
    }

    public int encode(OutputStream reverseOS) throws IOException {

        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                reverseOS.write(code[i]);
            }
            return code.length;
        }

        int codeLength = 0;
        if (exp != null) {
            codeLength += exp.encode(reverseOS, true);
            return codeLength;
        }

        if (con != null) {
            codeLength += con.encode(reverseOS, true);
            return codeLength;
        }

        throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
    }

    public int decode(InputStream is) throws IOException {
        return decode(is, null);
    }

    public int decode(InputStream is, BerTag berTag) throws IOException {

        int codeLength = 0;
        BerTag passedTag = berTag;

        if (berTag == null) {
            berTag = new BerTag();
            codeLength += berTag.decode(is);
        }

        if (berTag.equals(Constraint.tag)) {
            con = new Constraint();
            codeLength += con.decode(is, false);
            return codeLength;
        }

        if (berTag.equals(Expression.tag)) {
            exp = new Expression();
            codeLength += exp.decode(is, false);
            return codeLength;
        }

        if (passedTag != null) {
            return 0;
        }

        throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(reverseOS);
        code = reverseOS.getArray();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendAsString(sb, 0);
        return sb.toString();
    }

    public void appendAsString(StringBuilder sb, int indentLevel) {

        if (con != null) {
            sb.append("con: ");
            con.appendAsString(sb, indentLevel + 1);
            return;
        }

        if (exp != null) {
            sb.append("exp: ");
            exp.appendAsString(sb, indentLevel + 1);
            return;
        }

        sb.append("<none>");
    }

}

