/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;


public class SystemIdentity extends BerObjectIdentifier {

    public SystemIdentity() {
    }

    public SystemIdentity(byte[] code) {
        super(code);
    }

    public SystemIdentity(int[] value) {
        super(value);
    }

}
