/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package trustmessages.asn;

import org.openmuc.jasn1.ber.BerTag;
import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jasn1.ber.types.BerType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class Value implements BerType, Serializable {

    private static final long serialVersionUID = 1L;

    public byte[] code = null;
    public Entity source = null;
    public Entity target = null;
    public BinaryTime date = null;
    public Service service = null;

    public Value() {
    }

    public Value(byte[] code) {
        this.code = code;
    }

    public Value(Entity source, Entity target, BinaryTime date, Service service) {
        this.source = source;
        this.target = target;
        this.date = date;
        this.service = service;
    }

    public int encode(OutputStream reverseOS) throws IOException {

        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                reverseOS.write(code[i]);
            }
            return code.length;
        }

        int codeLength = 0;
        if (service != null) {
            codeLength += service.encode(reverseOS, false);
            // write tag: APPLICATION_CLASS, PRIMITIVE, 3
            reverseOS.write(0x43);
            codeLength += 1;
            return codeLength;
        }

        if (date != null) {
            codeLength += date.encode(reverseOS, false);
            // write tag: APPLICATION_CLASS, PRIMITIVE, 2
            reverseOS.write(0x42);
            codeLength += 1;
            return codeLength;
        }

        if (target != null) {
            codeLength += target.encode(reverseOS, false);
            // write tag: APPLICATION_CLASS, PRIMITIVE, 1
            reverseOS.write(0x41);
            codeLength += 1;
            return codeLength;
        }

        if (source != null) {
            codeLength += source.encode(reverseOS, false);
            // write tag: APPLICATION_CLASS, PRIMITIVE, 0
            reverseOS.write(0x40);
            codeLength += 1;
            return codeLength;
        }

        throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
    }

    public int decode(InputStream is) throws IOException {
        return decode(is, null);
    }

    public int decode(InputStream is, BerTag berTag) throws IOException {

        int codeLength = 0;
        BerTag passedTag = berTag;

        if (berTag == null) {
            berTag = new BerTag();
            codeLength += berTag.decode(is);
        }

        if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 0)) {
            source = new Entity();
            codeLength += source.decode(is, false);
            return codeLength;
        }

        if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 1)) {
            target = new Entity();
            codeLength += target.decode(is, false);
            return codeLength;
        }

        if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 2)) {
            date = new BinaryTime();
            codeLength += date.decode(is, false);
            return codeLength;
        }

        if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 3)) {
            service = new Service();
            codeLength += service.decode(is, false);
            return codeLength;
        }

        if (passedTag != null) {
            return 0;
        }

        throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(reverseOS);
        code = reverseOS.getArray();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendAsString(sb, 0);
        return sb.toString();
    }

    public void appendAsString(StringBuilder sb, int indentLevel) {

        if (source != null) {
            sb.append("source: ").append(source);
            return;
        }

        if (target != null) {
            sb.append("target: ").append(target);
            return;
        }

        if (date != null) {
            sb.append("date: ").append(date);
            return;
        }

        if (service != null) {
            sb.append("service: ").append(service);
            return;
        }

        sb.append("<none>");
    }

}

